export default{
  "login": "yash001dev",
  "id": 38398261,
  "node_id": "MDQ6VXNlcjM4Mzk4MjYx",
  "avatar_url": "https://avatars0.githubusercontent.com/u/38398261?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/yash001dev",
  "html_url": "https://github.com/yash001dev",
  "followers_url": "https://api.github.com/users/yash001dev/followers",
  "following_url": "https://api.github.com/users/yash001dev/following{/other_user}",
  "gists_url": "https://api.github.com/users/yash001dev/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/yash001dev/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/yash001dev/subscriptions",
  "organizations_url": "https://api.github.com/users/yash001dev/orgs",
  "repos_url": "https://api.github.com/users/yash001dev/repos",
  "events_url": "https://api.github.com/users/yash001dev/events{/privacy}",
  "received_events_url": "https://api.github.com/users/yash001dev/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Yash Sanghavi",
  "company": "GEC GANDHINAGAR",
  "blog": "www.linkedin.com/in/yash-sanghavi-a15460139",
  "location": "Ahmedabad",
  "email": null,
  "hireable": null,
  "bio": "Business Developer Of It Industry.\r\nCross-Platfrom Mobile Application Developer.\r\nPython Django Development Engineer.\r\nBasic Skills:Python,Java,JavaScript,CSS.",
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 0,
  "following": 10,
  "created_at": "2018-04-15T11:29:43Z",
  "updated_at": "2020-12-01T05:41:57Z"
}
